name = "astonishedliker/hypertext"
version = "0.1.0"
description = "A comprehensive set of utilities for Roblox RichText"
authors = ["AstonishedLiker"]
repository = "https://github.com/AstonishedLiker/HyperText"
license = "MIT"

includes = [
    "src/**",
    ".luaurc",
    "pesde.toml",
    "LICENSE.txt",
    "README.md"
]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
lune = "=0.8.9"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
build = "scripts/build.luau"
test = "scripts/test.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.1", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1" }

[dependencies]
t = { name = "glaphyre/t", version = "^1.0.0", target = "luau" }
darklua = { name = "pesde/darklua", version = "^0.17.1" }
